{{- range .Values.storageClasses }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: {{ .provisioner }}
reclaimPolicy: {{ .reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ .volumeBindingMode | default "WaitForFirstConsumer" }}
allowVolumeExpansion: {{ .allowVolumeExpansion | default true }}
parameters:
  {{- range $k, $v := .parameters }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
